name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make testsuite.install
      - name: Test with pytest
        run: |
          make testsuite.run
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Python-v${{ matrix.python-version }}
          files: ./coverage.xml
  package:
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check For Version Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=match::true
          fi
      - name: Set up Python
        if: steps.check-tag.outputs.match == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Packaging Tools
        if: steps.check-tag.outputs.match == 'true'
        run: |
          make package.install
      - name: Build Package
        if: steps.check-tag.outputs.match == 'true'
        run: |
          make package.build
      - name: Publish package to PyPi
        if: steps.check-tag.outputs.match == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN}}
